### ISSUE TITLE
Does not work with generating texts?

### ISSUE THREAD

**Issue by tuetschek** [UFAL-DSG/tgen#17]
```
Sun Mar 26 17:09:38 2017 INFO: Loading saved TF session from model.tfsess...
Sun Mar 26 17:09:47 2017 INFO: Generating...
Sun Mar 26 17:13:09 2017 INFO: Generated tree 100
Sun Mar 26 17:16:07 2017 INFO: Generated tree 200
Sun Mar 26 17:19:08 2017 INFO: Generated tree 300
Sun Mar 26 17:21:12 2017 INFO: Slot error: 1.000000 (M: 691, S: 0, T: 691)
Sun Mar 26 17:21:12 2017 INFO: Writing output...
Traceback (most recent call last):
  File "../run_tgen.py", line 592, in <module>
    seq2seq_gen(args)
  File "../run_tgen.py", line 513, in seq2seq_gen
    postprocess_tokens(gen_toks, das)
  File "/home/gila/anaconda2/lib/python2.7/tgen-ACL2016/tgen/futil.py", line 249, in postprocess_tokens
    final_punct = '?' if da[0].da_type[0] == '?' else '.'  # '?' for '?request...'
AttributeError: 'list' object has no attribute 'da_type'
```

**Comment by tuetschek** [comment]
Fixed in 782204339a38a1b7d9e8b3e1fe820903184c58bf .
